In [1]:
import cv2 as cv
import numpy as np

In [2]:
print(cv.__version__)

4.9.0


In [3]:
img = cv.imread('test.jpg',0) 
print(img)

[[ 68  70  73 ...  85  86  86]
 [ 68  70  73 ...  89  89  89]
 [ 69  71  74 ...  92  92  93]
 ...
 [ 53  39  27 ... 153 152 152]
 [ 51  46  37 ... 153 152 152]
 [ 47  52  45 ... 153 152 152]]


In [4]:
cv.imshow('person', img)
cv.waitKey(0)
cv.destroyAllWindows()

In [9]:
trainedData = cv.CascadeClassifier('haarcascade_frontalface_default.xml')
image = cv.imread('samplelady.jpg')
#image = cv.imread('sample2.jpg')
gray = cv.cvtColor(image, cv.COLOR_BGR2GRAY)
faceCoord = trainedData.detectMultiScale(gray)
print(faceCoord)
print("\r")
print(f'Number of faces found = {len(faceCoord)}')
for x,y,w,h in faceCoord:
    cv.rectangle(image, (x,y), (x+w, y+h), (0,255,0), 2)
cv.imshow('Face Detection', image)
cv.waitKey()
cv.destroyAllWindows()

[[138 109 208 208]]

Number of faces found = 1
